runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /(.*\.(html|js))$
  static_files: page/\1
  upload: page/.*\.(html|js)$

- url: /(.*/)*$
  static_files: page/\1/index.html
  upload: page/.*\.(html|js)$

- url: /.*
  script: _go_app
